import test from 'node:test'
import assert from 'node:assert/strict'

import { buildAuthWiringState } from './auth-wiring-state.js'

test('buildAuthWiringState resolves same-origin auth endpoints under an app base path', () => {
  assert.deepEqual(
    buildAuthWiringState({
      loginEndpoint: '/api/auth/login',
      signupEndpoint: '/api/auth/signup',
      sessionEndpoint: '/api/auth/session',
      pendingEndpoint: '/api/auth/pending',
      continueEndpoint: '/api/auth/continue',
      logoutEndpoint: '/api/auth/logout',
      appBasePath: '/github-pages-react-hello/',
      currentOrigin: 'https://havenly.example.com',
      credentialsMode: 'include',
      source: 'default',
      isConfigured: false,
    }),
    {
      source: 'default',
      credentialsMode: 'include',
      apiBaseUrl: null,
      appBasePath: '/github-pages-react-hello/',
      isConfigured: false,
      targets: {
        login: {
          endpoint: '/api/auth/login',
          resolvedUrl: '/github-pages-react-hello/api/auth/login',
          mode: 'same-origin',
          method: 'POST',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: true,
          carriesDraftSave: true,
          carriesGuestDraftSnapshot: true,
          carriesContinuation: true,
          isContinuation: false,
        },
        signup: {
          endpoint: '/api/auth/signup',
          resolvedUrl: '/github-pages-react-hello/api/auth/signup',
          mode: 'same-origin',
          method: 'POST',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: true,
          carriesDraftSave: true,
          carriesGuestDraftSnapshot: true,
          carriesContinuation: true,
          isContinuation: false,
        },
        session: {
          endpoint: '/api/auth/session',
          resolvedUrl: '/github-pages-react-hello/api/auth/session',
          mode: 'same-origin',
          method: 'GET',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: false,
          carriesDraftSave: false,
          carriesGuestDraftSnapshot: false,
          carriesContinuation: false,
          isContinuation: false,
        },
        pending: {
          endpoint: '/api/auth/pending',
          resolvedUrl: '/github-pages-react-hello/api/auth/pending',
          mode: 'same-origin',
          method: 'GET',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: false,
          carriesDraftSave: false,
          carriesGuestDraftSnapshot: false,
          carriesContinuation: false,
          isContinuation: false,
        },
        continue: {
          endpoint: '/api/auth/continue',
          resolvedUrl: '/github-pages-react-hello/api/auth/continue',
          mode: 'same-origin',
          method: 'POST',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: true,
          carriesDraftSave: true,
          carriesGuestDraftSnapshot: false,
          carriesContinuation: true,
          isContinuation: true,
        },
        logout: {
          endpoint: '/api/auth/logout',
          resolvedUrl: '/github-pages-react-hello/api/auth/logout',
          mode: 'same-origin',
          method: 'POST',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: true,
          carriesDraftSave: false,
          carriesGuestDraftSnapshot: false,
          carriesContinuation: false,
          isContinuation: false,
        },
      },
      scaffoldStrategy: 'same-origin-continuation-scaffold',
    },
  )
})

test('buildAuthWiringState keeps legacy api base config on the same frontend scaffold targets', () => {
  assert.deepEqual(
    buildAuthWiringState({
      apiBaseUrl: 'https://auth-runtime.example.com',
      loginEndpoint: '/v2/runtime/login',
      signupEndpoint: '/v2/runtime/signup',
      sessionEndpoint: '/v2/runtime/session',
      pendingEndpoint: '/v2/runtime/pending',
      continueEndpoint: '/v2/runtime/continue',
      logoutEndpoint: '/v2/runtime/logout',
      credentialsMode: 'omit',
      source: 'runtime',
      isConfigured: true,
    }),
    {
      source: 'runtime',
      credentialsMode: 'omit',
      apiBaseUrl: 'https://auth-runtime.example.com',
      appBasePath: '/',
      isConfigured: true,
      targets: {
        login: {
          endpoint: '/v2/runtime/login',
          resolvedUrl: '/v2/runtime/login',
          mode: 'same-origin',
          method: 'POST',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: true,
          carriesDraftSave: true,
          carriesGuestDraftSnapshot: true,
          carriesContinuation: true,
          isContinuation: false,
        },
        signup: {
          endpoint: '/v2/runtime/signup',
          resolvedUrl: '/v2/runtime/signup',
          mode: 'same-origin',
          method: 'POST',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: true,
          carriesDraftSave: true,
          carriesGuestDraftSnapshot: true,
          carriesContinuation: true,
          isContinuation: false,
        },
        session: {
          endpoint: '/v2/runtime/session',
          resolvedUrl: '/v2/runtime/session',
          mode: 'same-origin',
          method: 'GET',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: false,
          carriesDraftSave: false,
          carriesGuestDraftSnapshot: false,
          carriesContinuation: false,
          isContinuation: false,
        },
        pending: {
          endpoint: '/v2/runtime/pending',
          resolvedUrl: '/v2/runtime/pending',
          mode: 'same-origin',
          method: 'GET',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: false,
          carriesDraftSave: false,
          carriesGuestDraftSnapshot: false,
          carriesContinuation: false,
          isContinuation: false,
        },
        continue: {
          endpoint: '/v2/runtime/continue',
          resolvedUrl: '/v2/runtime/continue',
          mode: 'same-origin',
          method: 'POST',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: true,
          carriesDraftSave: true,
          carriesGuestDraftSnapshot: false,
          carriesContinuation: true,
          isContinuation: true,
        },
        logout: {
          endpoint: '/v2/runtime/logout',
          resolvedUrl: '/v2/runtime/logout',
          mode: 'same-origin',
          method: 'POST',
          targetLabel: 'same-origin /api auth scaffold',
          isSameOriginScaffold: true,
          expectsSerializableHandoff: true,
          carriesDraftSave: false,
          carriesGuestDraftSnapshot: false,
          carriesContinuation: false,
          isContinuation: false,
        },
      },
      scaffoldStrategy: 'same-origin-continuation-scaffold',
    },
  )
})
